import {
  MuiAccordion,
  MuiAlert,
  MuiAutocomplete,
  MuiAvatar,
  MuiAvatarGroup,
  MuiBackdrop,
  MuiButton,
  MuiButtonBase,
  MuiCardHeader,
  MuiChip,
  MuiCssBaseline,
  MuiDivider,
  MuiFormHelperText,
  MuiIconButton,
  MuiLinearProgress,
  MuiLink,
  MuiList,
  MuiListItem,
  MuiListItemAvatar,
  MuiListItemButton,
  MuiListItemText,
  MuiListSubheader,
  MuiMenu,
  MuiMenuItem,
  MuiOutlinedInput,
  MuiPaginationItem,
  MuiPaper,
  MuiRadio,
  MuiSelect,
  MuiSlider,
  MuiStepIcon,
  MuiStepper,
  MuiSwitch,
  MuiTab,
  MuiTableCell,
  MuiTablePagination,
  MuiTableRow,
  MuiTabs,
  MuiTextField,
  MuiTimelineConnector,
  MuiTimelineDot,
  MuiTimelineItem,
  MuiToggleButton,
  MuiToolbar,
  MuiTooltip,
  MuiTypography,
} from "@/themes/lightSchema/components";
import { Components, createTheme, Theme } from "@mui/material";

import { breakpoints, colors, palette, typography } from "@/themes/lightSchema";

export const components: Components<Omit<Theme, "components">> & {
  MuiTimelineDot: any;
  MuiTimelineItem: any;
  MuiTimelineConnector: any;
} = {
  MuiTextField,
  MuiBackdrop,
  MuiFormHelperText,
  MuiCssBaseline,
  MuiSelect,
  MuiOutlinedInput,
  MuiListSubheader,
  MuiCardHeader,
  MuiRadio,
  MuiChip,
  MuiAccordion,
  MuiAvatar,
  MuiAvatarGroup,
  MuiListItemAvatar,
  MuiPaginationItem,
  MuiButton,
  MuiButtonBase,
  MuiToggleButton,
  MuiIconButton,
  MuiListItemText,
  MuiListItemButton,
  MuiDivider,
  MuiPaper,
  MuiLink,
  MuiLinearProgress,
  MuiSlider,
  MuiList,
  MuiTab,
  MuiTabs,
  MuiMenu,
  MuiMenuItem,
  MuiListItem,
  MuiAutocomplete,
  MuiTablePagination,
  MuiToolbar,
  MuiTableRow,
  MuiTableCell,
  MuiAlert,
  MuiTooltip,
  MuiTimelineDot,
  MuiTimelineConnector,
  MuiTimelineItem,
  MuiSwitch,
  MuiStepper,
  MuiStepIcon,
  MuiTypography,
};

const lightTheme = createTheme({
  colors,
  palette,
  breakpoints,
  components,
  spacing: 9,
  shape: {
    borderRadius: 10,
  },
  typography,
  shadows: [
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
    "none",
  ],
});

export default lightTheme;
