"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const permission_controller_1 = require("../controllers/permission.controller");
const router = (0, express_1.Router)();
router.get("/users", permission_controller_1.permissionsUserHandler);
router.get("/exchanges", permission_controller_1.permissionsExchangeHandler);
router.get("/products", permission_controller_1.permissionsProductsHandler);
router.get("/brands", permission_controller_1.permissionsBrandsHandler);
router.get("/category", permission_controller_1.permissionsCategoriesHandler);
router.get("/sales-category", permission_controller_1.permissionsSalesCategoriesHandler);
exports.default = router;
